[project]
name = "cpptb-codegen"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
  "pyslang==11.0.0",
]

[project.scripts]
cpptb-codegen = "cpptb_codegen.generate_dpi_bindings:main"

[build-system]
requires = ["setuptools>=69"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "tools/codegen"}

[tool.setuptools.packages.find]
where = ["tools/codegen"]
include = ["cpptb_codegen*"]
