[project]
name = "cpptb-codegen"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
  "pyslang==11.0.0",
  "PyYAML>=6,<7",
  "cpptb-peakrdl",
]

[project.optional-dependencies]
peakrdl = [
  "cpptb-peakrdl[peakrdl,ipxact]",
]

[project.scripts]
cpptb = "cpptb_codegen.cli:main"
cpptb-codegen = "cpptb_codegen.generate_dpi_bindings:main"
cpptb-run = "cpptb_codegen.runner:main"
cpptb-rggen = "cpptb_codegen.rggen_codegen:main"

[build-system]
requires = ["setuptools>=69"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "tools/codegen"}

[tool.setuptools.packages.find]
where = ["tools/codegen"]
include = ["cpptb_codegen*"]

[tool.setuptools.data-files]
"include/cpptb" = ["include/cpptb/*.hpp"]
"include/cpptb/sv" = ["include/cpptb/sv/*.cpp", "include/cpptb/sv/*.sv", "include/cpptb/sv/*.svh"]
"include/cpptb_vc" = ["include/cpptb_vc/*.hpp"]

[dependency-groups]
docs = [
    "furo>=2025.12.19",
    "myst-parser>=5.1.0",
    "sphinx>=9.0.4",
    "zensical>=0.0.50",
]

[tool.uv]
default-groups = []

[tool.uv.workspace]
members = ["tools/peakrdl"]

[tool.uv.sources]
cpptb-peakrdl = { workspace = true }
