from __future__ import annotations

import unittest
from types import SimpleNamespace

from cpptb_codegen.register_codegen import (
    Field,
    Memory,
    Register,
    RegisterBlock,
    RegisterCodegenError,
    _integer_reset,
    _mapped_property,
    _member_names,
    _require_model_width,
    cpp_identifier,
    render_cpp,
)


class FakeNode:
    width = 8

    def get_path(self) -> str:
        return "demo.control.value"


class RegisterCodegenUnitTests(unittest.TestCase):
    @staticmethod
    def field(name: str, path: str) -> Field:
        return Field(
            name=name,
            path=path,
            lsb=0,
            width=1,
            access="cpptb::vc::RegisterAccess::ReadWrite",
            read_effect="cpptb::vc::RegisterReadEffect::None",
            write_effect="cpptb::vc::RegisterWriteEffect::None",
            reset_value=0,
            reset_mask=0,
            volatile=False,
        )

    def test_cpp_identifier_and_member_collision_rules_are_stable(self) -> None:
        self.assertEqual(cpp_identifier("9-mode/value"), "n_9_mode_value")
        self.assertEqual(cpp_identifier("class"), "class_")
        self.assertEqual(
            _member_names(["demo.a-b", "demo.a_b", "demo.a.b"]),
            ["a_b", "a_b_2", "a_b_3"],
        )
        self.assertEqual(
            _member_names(["demo.reset_all"], reserved={"reset_all"}),
            ["reset_all_2"],
        )

    def test_rendered_header_is_qualified_and_records_access_width(self) -> None:
        field = Field(
            name="value",
            path="demo.control.value",
            lsb=0,
            width=8,
            access="cpptb::vc::RegisterAccess::ReadWrite",
            read_effect="cpptb::vc::RegisterReadEffect::None",
            write_effect="cpptb::vc::RegisterWriteEffect::None",
            reset_value=3,
            reset_mask=0xFF,
            volatile=False,
        )
        block = RegisterBlock(
            name="demo",
            registers=(
                Register(
                    name="control",
                    member="control",
                    path="demo.control",
                    address=4,
                    width=32,
                    access_width=16,
                    endianness="cpptb::vc::RegisterEndianness::Little",
                    reset_value=3,
                    reset_mask=0xFF,
                    fields=(field,),
                ),
            ),
            memories=(
                Memory(
                    name="ram",
                    member="ram",
                    path="demo.ram",
                    address=0x100,
                    entries=4,
                    width=32,
                    access_width=32,
                    access="cpptb::vc::RegisterAccess::ReadWrite",
                ),
            ),
        )

        generated = render_cpp(block, "generated_demo", "RegModel")

        self.assertTrue(generated.startswith("// Generated by cpptb-codegen 0.1.0."))
        self.assertNotIn("using namespace cpptb::vc", generated)
        self.assertIn(".access_width = 16", generated)
        self.assertIn(
            ".endianness = cpptb::vc::RegisterEndianness::Little", generated
        )
        self.assertIn("cpptb::vc::RegisterHandle<Master>", generated)
        self.assertIn("cpptb::vc::RegisterMemoryHandle<Master> ram", generated)

    def test_reset_reference_error_includes_the_node_path(self) -> None:
        with self.assertRaisesRegex(
            RegisterCodegenError,
            r"demo\.control\.value: reset references are not supported",
        ):
            _integer_reset(object(), FakeNode())

    def test_unknown_property_error_includes_property_and_path(self) -> None:
        with self.assertRaisesRegex(
            RegisterCodegenError,
            r"demo\.control\.value: unsupported SystemRDL sw value future",
        ):
            _mapped_property({}, SimpleNamespace(name="future"), "sw", FakeNode())

    def test_unrepresentable_width_error_is_contextual(self) -> None:
        with self.assertRaisesRegex(
            RegisterCodegenError,
            r"demo\.wide: register width 65536.*65535-bit descriptor",
        ):
            _require_model_width(65536, "demo.wide", "register")

    def test_field_members_avoid_keywords_collisions_and_handle_methods(self) -> None:
        fields = (
            self.field("class", "demo.control.class"),
            self.field("class_", "demo.control.class_"),
            self.field("read", "demo.control.read"),
        )
        block = RegisterBlock(
            name="demo",
            registers=(
                Register(
                    name="control",
                    member="control",
                    path="demo.control",
                    address=0,
                    width=32,
                    access_width=32,
                    endianness="cpptb::vc::RegisterEndianness::Little",
                    reset_value=0,
                    reset_mask=0,
                    fields=fields,
                ),
            ),
            memories=(),
        )
        generated = render_cpp(block, "demo", "RegModel")
        self.assertIn("RegisterFieldHandle<Master> class_;", generated)
        self.assertIn("RegisterFieldHandle<Master> class__2;", generated)
        self.assertIn("RegisterFieldHandle<Master> read_2;", generated)

    def test_ambiguous_hierarchy_type_names_are_rejected(self) -> None:
        def register(path: str, member: str) -> Register:
            return Register(
                name=path.rsplit(".", 1)[-1],
                member=member,
                path=path,
                address=0 if member == "first" else 4,
                width=32,
                access_width=32,
                endianness="cpptb::vc::RegisterEndianness::Little",
                reset_value=0,
                reset_mask=0,
                fields=(),
            )

        block = RegisterBlock(
            name="demo",
            registers=(
                register("demo.a.b_c.value", "first"),
                register("demo.a_b.c.value", "second"),
            ),
            memories=(),
        )
        with self.assertRaisesRegex(
            RegisterCodegenError, "hierarchy type names collide"
        ):
            render_cpp(block, "demo", "RegModel")


if __name__ == "__main__":
    unittest.main()
