// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

module apb_event_sleep_unit_regs_core (
        input wire clk,
        input wire arst_n,

        input wire s_cpuif_req,
        input wire s_cpuif_req_is_wr,
        input wire [2:0] s_cpuif_addr,
        input wire [31:0] s_cpuif_wr_data,
        input wire [31:0] s_cpuif_wr_biten,
        output wire s_cpuif_req_stall_wr,
        output wire s_cpuif_req_stall_rd,
        output wire s_cpuif_rd_ack,
        output wire s_cpuif_rd_err,
        output wire [31:0] s_cpuif_rd_data,
        output wire s_cpuif_wr_ack,
        output wire s_cpuif_wr_err,

        input apb_event_sleep_unit_regs_core_pkg::apb_event_sleep_unit__in_t hwif_in,
        output apb_event_sleep_unit_regs_core_pkg::apb_event_sleep_unit__out_t hwif_out
    );

    //--------------------------------------------------------------------------
    // CPU Bus interface logic
    //--------------------------------------------------------------------------
    logic cpuif_req;
    logic cpuif_req_is_wr;
    logic [2:0] cpuif_addr;
    logic [31:0] cpuif_wr_data;
    logic [31:0] cpuif_wr_biten;
    logic cpuif_req_stall_wr;
    logic cpuif_req_stall_rd;

    logic cpuif_rd_ack;
    logic cpuif_rd_err;
    logic [31:0] cpuif_rd_data;

    logic cpuif_wr_ack;
    logic cpuif_wr_err;

    assign cpuif_req = s_cpuif_req;
    assign cpuif_req_is_wr = s_cpuif_req_is_wr;
    assign cpuif_addr = s_cpuif_addr;
    assign cpuif_wr_data = s_cpuif_wr_data;
    assign cpuif_wr_biten = s_cpuif_wr_biten;
    assign s_cpuif_req_stall_wr = cpuif_req_stall_wr;
    assign s_cpuif_req_stall_rd = cpuif_req_stall_rd;
    assign s_cpuif_rd_ack = cpuif_rd_ack;
    assign s_cpuif_rd_err = cpuif_rd_err;
    assign s_cpuif_rd_data = cpuif_rd_data;
    assign s_cpuif_wr_ack = cpuif_wr_ack;
    assign s_cpuif_wr_err = cpuif_wr_err;

    logic cpuif_req_masked;

    // Read & write latencies are balanced. Stalls not required
    assign cpuif_req_stall_rd = '0;
    assign cpuif_req_stall_wr = '0;
    assign cpuif_req_masked = cpuif_req
                            & !(!cpuif_req_is_wr & cpuif_req_stall_rd)
                            & !(cpuif_req_is_wr & cpuif_req_stall_wr);

    //--------------------------------------------------------------------------
    // Address Decode
    //--------------------------------------------------------------------------
    typedef struct {
        logic sleep_ctrl;
        logic sleep_status;
    } decoded_reg_strb_t;
    decoded_reg_strb_t decoded_reg_strb;
    logic decoded_err;
    logic [2:0] decoded_addr;
    logic decoded_req;
    logic decoded_req_is_wr;
    logic [31:0] decoded_wr_data;
    logic [31:0] decoded_wr_biten;

    always_comb begin
        automatic logic is_valid_addr;
        automatic logic is_valid_rw;
        is_valid_addr = '1; // No valid address check
        is_valid_rw = '1; // No valid RW check
        decoded_reg_strb.sleep_ctrl = cpuif_req_masked & (cpuif_addr == 3'h0) & ((!cpuif_req_is_wr & 1'b1 & 1'b1) | (cpuif_req_is_wr & 1'b1 & 1'b1));
        decoded_reg_strb.sleep_status = cpuif_req_masked & (cpuif_addr == 3'h4) & !cpuif_req_is_wr & 1'b1 & 1'b1;
        decoded_err = '0;
    end

    // Pass down signals to next stage
    assign decoded_addr = cpuif_addr;
    assign decoded_req = cpuif_req_masked;
    assign decoded_req_is_wr = cpuif_req_is_wr;
    assign decoded_wr_data = cpuif_wr_data;
    assign decoded_wr_biten = cpuif_wr_biten;


    //--------------------------------------------------------------------------
    // Field logic
    //--------------------------------------------------------------------------
    typedef struct {
        logic [31:0] next;
        logic load_next;
    } apb_event_sleep_unit__sleep_ctrl__value__field_combo_t;

    typedef struct {
        apb_event_sleep_unit__sleep_ctrl__value__field_combo_t value;
    } apb_event_sleep_unit__sleep_ctrl__field_combo_t;

    typedef struct {
        logic [31:0] next;
        logic load_next;
    } apb_event_sleep_unit__sleep_status__value__field_combo_t;

    typedef struct {
        apb_event_sleep_unit__sleep_status__value__field_combo_t value;
    } apb_event_sleep_unit__sleep_status__field_combo_t;

    typedef struct {
        apb_event_sleep_unit__sleep_ctrl__field_combo_t sleep_ctrl;
        apb_event_sleep_unit__sleep_status__field_combo_t sleep_status;
    } field_combo_t;
    field_combo_t field_combo;

    typedef struct {
        logic [31:0] value;
    } apb_event_sleep_unit__sleep_ctrl__value__field_storage_t;

    typedef struct {
        apb_event_sleep_unit__sleep_ctrl__value__field_storage_t value;
    } apb_event_sleep_unit__sleep_ctrl__field_storage_t;

    typedef struct {
        logic [31:0] value;
    } apb_event_sleep_unit__sleep_status__value__field_storage_t;

    typedef struct {
        apb_event_sleep_unit__sleep_status__value__field_storage_t value;
    } apb_event_sleep_unit__sleep_status__field_storage_t;

    typedef struct {
        apb_event_sleep_unit__sleep_ctrl__field_storage_t sleep_ctrl;
        apb_event_sleep_unit__sleep_status__field_storage_t sleep_status;
    } field_storage_t;
    field_storage_t field_storage;
    // Field: apb_event_sleep_unit.sleep_ctrl.value
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.sleep_ctrl.value.value;
        load_next_c = '0;
        if(decoded_reg_strb.sleep_ctrl && decoded_req_is_wr && 1'b1) begin // SW write
            next_c = (field_storage.sleep_ctrl.value.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end else if(hwif_in.sleep_ctrl.value.we) begin // HW Write - we
            next_c = hwif_in.sleep_ctrl.value.next;
            load_next_c = '1;
        end
        field_combo.sleep_ctrl.value.next = next_c;
        field_combo.sleep_ctrl.value.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.sleep_ctrl.value.value <= 32'h0;
        end else begin
            if(field_combo.sleep_ctrl.value.load_next) begin
                field_storage.sleep_ctrl.value.value <= field_combo.sleep_ctrl.value.next;
            end
        end
    end
    assign hwif_out.sleep_ctrl.value.value = field_storage.sleep_ctrl.value.value;
    // Field: apb_event_sleep_unit.sleep_status.value
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.sleep_status.value.value;
        load_next_c = '0;
        if(hwif_in.sleep_status.value.we) begin // HW Write - we
            next_c = hwif_in.sleep_status.value.next;
            load_next_c = '1;
        end
        field_combo.sleep_status.value.next = next_c;
        field_combo.sleep_status.value.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.sleep_status.value.value <= 32'h0;
        end else begin
            if(field_combo.sleep_status.value.load_next) begin
                field_storage.sleep_status.value.value <= field_combo.sleep_status.value.next;
            end
        end
    end
    assign hwif_out.sleep_status.value.value = field_storage.sleep_status.value.value;

    //--------------------------------------------------------------------------
    // Write response
    //--------------------------------------------------------------------------
    assign cpuif_wr_ack = decoded_req & decoded_req_is_wr;
    // Writes are always granted with no error response, unless an optional
    // policy check reports one.
    assign cpuif_wr_err = '0;

    //--------------------------------------------------------------------------
    // Readback
    //--------------------------------------------------------------------------

    logic [2:0] rd_mux_addr;
    assign rd_mux_addr = decoded_addr;

    logic readback_err;
    logic readback_done;
    logic [31:0] readback_data;
    always_comb begin
        automatic logic [31:0] readback_data_var;
        readback_data_var = '0;
        if((rd_mux_addr == 3'h0) && (decoded_reg_strb.sleep_ctrl)) begin
            readback_data_var[31:0] = field_storage.sleep_ctrl.value.value;
        end
        if((rd_mux_addr == 3'h4) && (decoded_reg_strb.sleep_status)) begin
            readback_data_var[31:0] = field_storage.sleep_status.value.value;
        end
        readback_data = readback_data_var;
        readback_done = decoded_req & ~decoded_req_is_wr;
        readback_err = '0;
    end

    assign cpuif_rd_ack = readback_done;
    assign cpuif_rd_data = readback_data;
    assign cpuif_rd_err = readback_err;
endmodule
