// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package apb_event_service_unit_regs_core_pkg;

    localparam APB_EVENT_SERVICE_UNIT_REGS_CORE_DATA_WIDTH = 32;
    localparam APB_EVENT_SERVICE_UNIT_REGS_CORE_MIN_ADDR_WIDTH = 4;
    localparam APB_EVENT_SERVICE_UNIT_REGS_CORE_SIZE = 'h10;

    typedef struct {
        logic [31:0] next;
        logic we;
    } apb_event_service_unit__rw32_t__value__in_t;

    typedef struct {
        apb_event_service_unit__rw32_t__value__in_t value;
    } apb_event_service_unit__rw32_t__in_t;

    typedef struct {
        logic [31:0] next;
        logic we;
    } apb_event_service_unit__wo32_t__value__in_t;

    typedef struct {
        apb_event_service_unit__wo32_t__value__in_t value;
    } apb_event_service_unit__wo32_t__in_t;

    typedef struct {
        apb_event_service_unit__rw32_t__in_t enable;
        apb_event_service_unit__rw32_t__in_t pending;
        apb_event_service_unit__wo32_t__in_t set_pending;
        apb_event_service_unit__wo32_t__in_t clear_pending;
    } apb_event_service_unit__in_t;

    typedef struct {
        logic [31:0] value;
    } apb_event_service_unit__rw32_t__value__out_t;

    typedef struct {
        apb_event_service_unit__rw32_t__value__out_t value;
    } apb_event_service_unit__rw32_t__out_t;

    typedef struct {
        logic [31:0] value;
        logic wr_swacc;
    } apb_event_service_unit__wo32_t__value__out_t;

    typedef struct {
        apb_event_service_unit__wo32_t__value__out_t value;
    } apb_event_service_unit__wo32_t__out_t;

    typedef struct {
        apb_event_service_unit__rw32_t__out_t enable;
        apb_event_service_unit__rw32_t__out_t pending;
        apb_event_service_unit__wo32_t__out_t set_pending;
        apb_event_service_unit__wo32_t__out_t clear_pending;
    } apb_event_service_unit__out_t;
endpackage
